[package]
name = "vector_db"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
thiserror = "1"
parking_lot = "0.12"
hnsw_rs = "0.3.2"
memmap2 = "0.9"
byteorder = "1"
dotenvy = "0.15"

